CREATE SCHEMA COURSES_DB;
USE COURSES_DB;

CREATE TABLE IF NOT EXISTS `course`(ID INT, NAME VARCHAR(50),
PRIMARY KEY(ID));

CREATE TABLE IF NOT EXISTS `student`(ID INT, COURSEID INT, NAME VARCHAR(50),
 AGE INT, GENDER VARCHAR(1), PRIMARY KEY(ID), FOREIGN KEY (COURSEID) REFERENCES course(ID));


ALTER TABLE course MODIFY NAME VARCHAR(50) NOT NULL;
ALTER TABLE course MODIFY ID INT AUTO_INCREMENT NOT NULL;
ALTER TABLE student MODIFY ID INT AUTO_INCREMENT  NOT NULL;
ALTER TABLE student ADD RUT VARCHAR(10) NOT NULL UNIQUE;